services:
  wca-states-db:
    build: ./db
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - internal

  wca-states-updater:
    build: ./updater
    volumes:
      - ./data/pos_processing.sql:/pos_processing.sql
    environment:
      - MYSQL_HOST=wca-states-db
    env_file:
      - .env
    depends_on:
      - wca-states-db
    networks:
      - internal

  wca-states-server:
    build: ./server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - GIN_MODE=release
      - GORM_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(wca-states-db:${MYSQL_PORT})/${MYSQL_DATABASE}?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      wca-states-db:
        condition: service_healthy
    networks:
      - internal
  
  wca-states-front:
    build: ./front
    ports:
      - ${FRONT_PORT}:3000
    networks:
      - internal

networks:
  internal:
    external: true
